### ISSUE TITLE
Latest wotlk version throwing error.

### ISSUE THREAD

**Issue by gelsbern** [TheKrowi/Krowi_AchievementFilter#81] opened 2022-11-24 14:57 UTC
1x Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:33: attempt to call method 'Load' (a nil value)
[string "@Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua"]:33: in function `LoadWithBlizzard_AchievementUI'
[string "@Interface\AddOns\Krowi_AchievementFilter\Krowi_AchievementFilter-48.3.lua"]:80: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:77>
[string "@Interface\AddOns\Krowi_AchievementFilter\Krowi_AchievementFilter-48.3.lua"]:122: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:111>

Locals:
self = <table> {
 HookShowSubFrame = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:74
 CategoriesFrame = KrowiAF_CategoriesFrame {
 }
 SetAchievementFrameHeight = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:141
 HookBaseTabOnClick = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:80
 PrepareTabsOrder = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:291
 RefreshView = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:452
 SummaryFrame = KrowiAF_AchievementFrameSummaryFrame {
 }
 AlertSystem = <table> {
 }
 ShowStatusBarTooltip = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:301
 LoadOldAchievementFrameTabsCompatibility = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:426
 SetCloseButtonOnKeyDown = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:116
 LoadWithAddon = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:11
 Tabs = <table> {
 }
 AchievementsObjectives = KrowiAF_AchievementsObjectives {
 }
 SelectedTab = AchievementFrameTab3 {
 }
 ResetAchievementWindowPosition = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:107
 ShowSubFrame = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:93
 SideButton = <table> {
 }
 FilterButton = KrowiAF_AchievementFrameFilterButton {
 }
 Calendar = <table> {
 }
 SetFrameToLastPosition = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:436
 SetAchievementFrameWidth = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:131
 Search = <table> {
 }
 RightClickMenu = <table> {
 }
 AchievementsFrame = KrowiAF_AchievementsFrame {
 }
 LoadOldAchievementFrameCompatibility = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:409
 TabsOrderGetActiveKeys = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:326
 AchievementTooltip = <table> {
 }
 AchievementFrameTabButton = <table> {
 }
 AddDataToBlizzardTabs = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:277
 GetSafeScrollChildBottom = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:155
 AchievementFrameHeader = <table> {
 }
 DataManagerFrame = KrowiAF_DataManagerFrame {
 }
 WorldMapButton = Krowi_WorldMapButtons2 {
 }
 SelectTab = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:183
 LoadWrathClassicAchievementFrameChanges = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:394
 LoadWithBlizzard_AchievementUI = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:22
 SubFrames = <table> {
 }
 ResetAchievementFrameHeight = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:148
 ShowHideTabs = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:232
 ToggleAchievementFrame = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:194
 GameTooltipProgressBar = Krowi_ProgressBar1 {
 }
 ResetAchievementFrameWidth = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:135
 SideButtonSystem = <table> {
 }
}
(*temporary) = nil
(*temporary) = KrowiAF_AchievementsObjectives {
 0 = <userdata>
 DisplayCriteria = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:313
 ResetProgressBars = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:18
 SetTextPoints = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:262
 ResetAll = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:33
 ResetMiniAchievements = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:22
 ResetTextCriteria = <function> def

**Comment by TheKrowi** [comment] 2022-11-24 17:53
Duplicate of #78

**Closed by TheKrowi** 2022-11-24 17:53 UTC
Labels: duplicate, wrath classic
