### ISSUE TITLE
Lua error on login

### ISSUE THREAD

**Issue by filliph** [TheKrowi/Krowi_AchievementFilter#41] opened 2022-10-27 13:30 UTC
```
1x Interface/AddOns/Krowi_AchievementFilter/API.lua:133: attempt to index local 'category' (a nil value)
[string "@Interface/AddOns/Krowi_AchievementFilter/API.lua"]:133: in function `KrowiAF_SelectCategory'
[string "@Interface/AddOns/Krowi_AchievementFilter/GUI/Misc/AlertFrame/AlertFrame.lua"]:13: in function <...AchievementFilter/GUI/Misc/AlertFrame/AlertFrame.lua:4>

Locals:
category = nil
collapsed = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'category' (a nil value)"
addon = <table> {
 ReplaceVarsWithReloadReq = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:514
 ExcludeAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:203
 Data = <table> {
 }
 UnitTests = <table> {
 }
 IsShadowlandsRetail = false
 WorldMapButtons = <table> {
 }
 DelayObjects = <table> {
 }
 GUI = <table> {
 }
 DelayFunction = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:650
 Filters = <table> {
 }
 GlobalStrings = <table> {
 }
 Objects = <table> {
 }
 Tutorials = <table> {
 }
 EventData = <table> {
 }
 OnAchievementEarned = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:347
 Options = <table> {
 }
 GetUsableSets = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:564
 Diagnostics = <table> {
 }
 Faction = <table> {
 }
 GetNextAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:534
 ExtraWrathStrings = <table> {
 }
 Colors = <table> {
 }
 BuildCache = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:313
 Libs = <table> {
 }
 GetCovenantName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:640
 Util = <table> {
 }
 MetaData = <table> {
 }
 GetFirstAchievementId = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:3
 TrackingAchievements = <table> {
 }
 GetInstanceInfoName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:612
 GetSecondsSince = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:504
 GetAchievementInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:523
 GetAchievementsInZone = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:20
 IsWrathClassic = false
 GetVariantSetIDs = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:576
 GetLFGDungeonInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:636
 ResetCache = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:343
 TabsOrder = <table> {
 }
 Tabs = <table> {
 }
 IncludeAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:182
 L = <table> {
 }
 Icon = <table> {
 }
 Credits = <table> {
 }
 GetActiveCovenant = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:16
 HookAchievementFrameOnShow = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:434
 GetAchievementNumbers = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:51
 GetMapName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:644
 FocusAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:155
 AddToTrackingAchievementsCategories = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:169
 Event = <table> {
 }
 GetCategoryInfoTitle = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:624
 IsDragonflightRetail = true
 ClearFocusAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:134
 ChangeAchievementMicroButtonOnClick = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:594
 InGuildView = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:12
 Localization = <table> {
 }
 Plugins = <table> {
 }
 MakeWindowMovable = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:471
 OverwriteFunctions = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:362
}
addonName = "Krowi_AchievementFilter"
SelectCategory = <function> defined @Interface/AddOns/Krowi_AchievementFilter/API.lua:91
```

**Comment by TheKrowi** [comment] 2022-10-27 15:40
It looks like you're clicking one of the event reminders that pop up when you log in. Which event are you clicking on? Can you please try the same thing with only KAF enabled? I'm not able to reproduce it with my setup.

**Comment by filliph** [comment] 2022-10-28 13:58
Sorry for the delay in getting back to you.

I thought it was happening on login, but as it turns out, I had actually left-clicked the Mogu assault pop-up:

![image](https://user-images.githubusercontent.com/9424286/198627937-440f6148-416f-4db5-8074-e48bb1033b8f.png)

I am able to replicate it 100% of the time after a `/reload` and clicking on this pop-up.

**Comment by TheKrowi** [comment] 2022-10-28 16:50
I'm sorry but I can't reproduce it on my end. Have you tried disabling all addons except for KAF and see if you have the same behavior?

**Comment by filliph** [comment] 2022-10-28 23:44
This might just have been a false alarm, seems like a conflict with [GW2_UI](https://www.curseforge.com/wow/addons/gw2-ui) which I'm helping test the DF version of.

I'd like to keep this issue open while I ask one of the devs about this, in case they would want you to make any changes to make the two add-ons work together, if that's okay with you? 🙂

**Comment by TheKrowi** [comment] 2022-10-29 03:08
Sure, I have a compatibility plugin for ElvUI so other UI mods will be considered too.

**Comment by TheKrowi** [comment] 2022-11-05 22:02
@filliph , any update?

Is there something I can do and develop a compatibility? If the latter, please close this one and create a new issue and/or discord suggestion.

**Comment by filliph** [comment] 2022-11-06 02:25
Sorry, the GW2 dev has been very busy trying to fix the various taint issues Blizz introduced 😅 I'll poke them to see if it's something that can be given a wee bit more priority 🙂

**Comment by TheKrowi** [comment] 2022-11-06 05:31
I'm more than happy to implement something similar like I did for ElvUI. I think it will depend who is looking into it, they or me :)

**Comment by TheKrowi** [comment] 2022-11-06 14:56
Another issue by some1 on curse



Hello, open the achievement window and you will see such an error，

After the test, it is found that there is an error with the Edit Mode Expanded plug-in. There is no problem with the 006 version of this plug-in. After the 007 version was updated, the hidden mini menu bar and backpack bar were added. This error occurred. I also contacted the author of Edit Mode Expanded to see what was going on. Foreign players, poor English, software translation, please forgive me.

 

12x Interface/AddOns/Krowi_AchievementFilter/API.lua:133: attempt to index local 'category' (a nil value)
[string "@Interface/AddOns/Krowi_AchievementFilter/API.lua"]:133: in function `KrowiAF_SelectCategory'
[string "@Interface/AddOns/Krowi_AchievementFilter/GUI/Misc/AlertFrame/AlertFrame.lua"]:13: in function <...AchievementFilter/GUI/Misc/AlertFrame/AlertFrame.lua:4>

Locals:
category = nil
collapsed = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'category' (a nil value)"
addon = <table> {
ReplaceVarsWithReloadReq = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:520
WorldMapButtons = <table> {
}
ExcludeAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:208
Data = <table> {
}
UnitTests = <table> {
}
GUI = <table> {
}
IsShadowlandsRetail = false
Filters = <table> {
}
DelayObjects = <table> {
}
GlobalStrings = <table> {
}
DelayFunction = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:656
Options = <table> {
}
Objects = <table> {
}
Tutorials = <table> {
}
TooltipData = <table> {
}
EventData = <table> {
}
OnAchievementEarned = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:351
Diagnostics = <table> {
}
GetUsableSets = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:570
Faction = <table> {
}
GetCovenantName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:646
GetNextAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:540
ExtraWrathStrings = <table> {
}
Colors = <table> {
}
BuildCache = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:317
Libs = <table> {
}
TrackingAchievements = <table> {
}
Util = <table> {
}
MetaData = <table> {
}
GetFirstAchievementId = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:3
GetInstanceInfoName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:618
IsWrathClassic = false
GetSecondsSince = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:510
GetAchievementInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:529
GetAchievementsInZone = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:20
MakeWindowStatic = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:466
GetVariantSetIDs = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:582
GetLFGDungeonInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:642
ResetCache = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:347
TabsOrder = <table> {
}
Tabs = <table> {
}
IncludeAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:185
L = <table> {
}
Icon = <table> {
}
Credits = <table> {
}
GetActiveCovenant = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:16
HookAchievementFrameOnShow = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:438
GetAchievementNumbers = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:51
GetMapName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:650
FocusAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:159
AddToTrackingAchievementsCategories = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:172
Event = <table> {
}
GetCategoryInfoTitle = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:630
IsDragonflightRetail = true
ClearFocusAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:136
ChangeAchievementMicroButtonOnClick = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:600
InGuildView = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:12
Localization = <table> {
}
Plugins = <table> {
}
MakeWindowMovable = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:503
OverwriteFunctions = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:366
}
addonNam

**Comment by teelolws** [comment] 2022-11-06 18:55
Ahh its cause I'm putting custom Events into that Enum. I'll find a different way to do that.

**Comment by TheKrowi** [comment] 2022-11-06 19:55
No clue how that could've caused this issue O.o

**Comment by teelolws** [comment] 2022-11-06 19:58
Its just a guess from this line of code, which is 13 on AlertFrame.lua, second line of the above error:

`    local category = KrowiAF_SelectCategory(self.Event.Category);`

I saw that and remembered that I added a custom Event to Blizzards Enum, which I should have changed earlier.

**Comment by teelolws** [comment] 2022-11-06 20:03
If thats not the problem (I don't know what triggered the Lua error; I did a bit of testing running both addons and couldn't get it to appear), it could be connected to loading the achievement frame during ADDON_LOADED?

`if ( not AchievementFrame ) then AchievementFrame_LoadUI() end`

**Comment by TheKrowi** [comment] 2022-11-06 20:05
That something you do? KAF relies on the fact that it can load some data first and then for the Blizzard_AchievementUI part to load. If it's the other way around it might cause this issue but not sure about that.

**Comment by teelolws** [comment] 2022-11-06 20:20
Yeah I have to. Its the only way I can guarantee the frame is actually usable. I could delay it to a later event, PLAYER_ENTERING_WORLD or something else if you prefer?

**Comment by TheKrowi** [comment] 2022-11-06 20:30
This error is related to `Blizzard_AchievementUI` loading before KAF is loaded. This is caused by another addon.

**Comment by TheKrowi** [comment] 2022-11-06 20:31
I'm going to look if I can fix it on my end cause you addon is not the only one causing it.

**Comment by TheKrowi** [comment] 2022-11-06 20:43
#62 was easy to fix, this one will require a little bit more digging as it's related to the event reminders and sidebuttons not loading.

**Closed** 2022-11-06 22:09 UTC
Labels: compatibility, bug, dragonflight

**Comment by teelolws** [comment] 2022-11-11 23:17
I'm going to delay `AchievementFrame_LoadUI()` until a later event, as its causing the Achievements Frame to not load Feats of Strength properly. You may want to check if the same bug happens with your addon.

**Comment by TheKrowi** [comment] 2022-11-12 11:40
KAF does not change loading orders, just hooks into it so it should be fine.
